//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace s4pi.ImageResource.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("s4pi.ImageResource.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x0580A2B4  THUM   .png
        ///0x0580A2B5  THUM   .png
        ///0x0580A2B6  THUM   .png
        ///0x0580A2CD  SNAP   .png
        ///0x0580A2CE  SNAP   .png
        ///0x0580A2CF  SNAP   .png
        ///0x0589DC44  THUM   .png
        ///0x0589DC45  THUM   .png
        ///0x0589DC46  THUM   .png
        ///0x0589DC47  THUM   .png
        ///0x05B17698  THUM   .png
        ///0x05B17699  THUM   .png
        ///0x05B1769A  THUM   .png
        ///0x05B1B524  THUM   .png
        ///0x05B1B525  THUM   .png
        ///0x05B1B526  THUM   .png
        ///0x0668F635  TWNI   .png
        ///0x2653E3C8  THUM   .png
        ///0x2653E3C9  THUM   .png
        ///0x2653E3CA  THUM   .png
        ///0x2D4284F0   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImageResources {
            get {
                return ResourceManager.GetString("ImageResources", resourceCulture);
            }
        }
    }
}
